### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by Kache** [volopivoshenko/poetry-plugin-dotenv#24]
- [X] I have searched the [issues] of this repository and believe that this is not a duplicate.
- [X] I have searched the [documentation] and believe that my question is not covered.

**Is your feature request related to a problem? Please describe.**

`poetry-dotenv` has an explicit [upper bound version constraint against Python 3.11](https://github.com/volopivoshenko/poetry-dotenv/blob/a0363ff7baebcdabe8d0641172827efcb11c4b4e/pyproject.toml#L51)

**Describe the solution you'd like**

Support Python 3.11

**Describe alternatives you've considered**

"Forking locally" to remove the `<3.11` constraint and see if it works.

**Additional context**

What's the reason for the upper bound? Does `poetry-dotenv` use [Python features removed in 3.11](https://docs.python.org/3/whatsnew/3.11.html#removed)?

If not, `<3.11` is overly conservative, as [Python will retain functionality for at least two minor versions](https://discuss.python.org/t/documenting-python-versioning-and-stability-expectations/11090#minor-versions-7), i.e. [at least two years](https://discuss.python.org/t/documenting-python-versioning-and-stability-expectations/11090#minor-versions-7).

**Comment by pivoshenko** [comment]
Done.
