### ISSUE TITLE
if config.ignore is always True

### ISSUE THREAD

**Issue by charleswilmot** [volopivoshenko/poetry-plugin-dotenv#317]
### Description

In plugin.py, config.ignore is a string == "false"

```
if "false":
    print("this is shown")
```

I had to manually change the code to

```
        if config.ignore in ["1", "true", "True"]:
            ...
```

To get the plugin to work.

### Workarounds

Fix the code

### Operating System

Ubuntu 22.04

### poetry version

1.8.3

### poetry-plugin-dotenv version

2.4

### Runtime logs

```bash session
Loading configuration file /home/***
Loading configuration file /home/***
Adding repository rapid (https://gitlab***) and setting it as supplemental
Using virtualenv: /home/***
Not loading environment variables.
```

**Comment by pivoshenko** [comment]
Hi @charleswilmot! Thanks for submitting the issue, I really appreciate the feedback

I wanted to apologize that I didn't have a chance to have a look into it, firstly was super busy with work and now I am ill, but once I will recover I will look into it!

Thanks again!

**Comment by charleswilmot** [comment]
Glad I can help!

The fix is really straightforward, I hope you'll find the time to ship it soon

**Comment by pivoshenko** [comment]
Hi @charleswilmot! First of all, I want to apologize for taking so much time to look into this issue (it was a crazy couple of weeks with a lot of stuff going around)!

I updated the config loader, please feel free to re-open the issue, is the issue is still in place.

thanks!
